apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
      - ./infrastructure/k8s-dev/*
build:
  local:
    push: true
  artifacts:
    - image: manelcastro/be-contact-form
      context: ./be-contact-form
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/be-auth
      context: ./be-auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/be-backoffice
      context: ./be-backoffice
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/fe-backoffice
      context: ./fe-backoffice
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "/**/*.ts"
            dest: .
          - src: "/**/*.tsx"
            dest: .
    - image: manelcastro/fe-client
      context: ./fe-client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "/**/*.ts"
            dest: .
          - src: "/**/*.tsx"
            dest: .
