apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-auth
  template:
    metadata:
      labels:
        app: be-auth
    spec:
      containers:
        - name: be-auth
          # image: us.gcr.io/ticketing-dev-359710/be-auth
          image: manelcastro/be-auth:latest
          env:
            - name: JWT_KEY
              value: "123456"
            - name: PORT
              value: "9001"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/postgresdb?schema=public&connect_timeout=300"
            - name: ADMIN_SIGNUP_KEY
              value: "123456"
            - name: SUPER_ADMIN_SIGNUP_KEY
              value: "654321"
            - name: USER_SIGNUP_KEY
              value: "111111"

---
apiVersion: v1
kind: Service
metadata:
  name: be-auth-srv
spec:
  selector:
    app: be-auth
  type: ClusterIP
  ports:
    - name: be-auth
      protocol: TCP
      port: 9001
      targetPort: 9001
