apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-backoffice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-backoffice
  template:
    metadata:
      labels:
        app: be-backoffice
    spec:
      initContainers:
      - name: check-db-ready-backoffice
        image: postgres:9.6.5
        command: ['sh', '-c', 
          'until pg_isready -h postgres-be-backoffice -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: be-backoffice
          # image: us.gcr.io/ticketing-dev-359710/be-auth
          image: manelcastro/be-backoffice
          env:
            - name: PORT
              value: "9002"
---
apiVersion: v1
kind: Service
metadata:
  name: be-backoffice-srv
spec:
  selector:
    app: be-backoffice
  type: ClusterIP
  ports:
    - name: be-backoffice
      protocol: TCP
      port: 9002
      targetPort: 9002
