apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-backoffice-alpha-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-backoffice-alpha
  template:
    metadata:
      labels:
        app: be-backoffice-alpha
    spec:
      initContainers:
        - name: check-db-ready-backoffice
          image: postgres:9.6.5
          command: [
              "sh",
              "-c",
              "until pg_isready -h postgres-be-backoffice-alpha -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: be-backoffice-alpha
          # image: us.gcr.io/ticketing-dev-359710/be-auth
          image: manelcastro/be-backoffice-alpha
          env:
            - name: PORT
              value: "9009"
---
apiVersion: v1
kind: Service
metadata:
  name: be-backoffice-alpha-srv
spec:
  selector:
    app: be-backoffice-alpha
  type: ClusterIP
  ports:
    - name: be-backoffice-alpha
      protocol: TCP
      port: 9009
      targetPort: 9009
