kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-be-backoffice-alpha-pv-volume # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: postgres-be-backoffice-alpha
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-be-backoffice-alpha-pv-claim # Sets name of PVC
  labels:
    app: postgres-be-backoffice-alpha
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
