apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-be-contact-form
  labels:
    app: postgres-be-contact-form
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
