# This is a basic workflow to help you get started with Actions
# FOLLOWED GUIDE! https://learn.microsoft.com/en-us/training/modules/aks-deployment-pipeline-github-actions/10-exercise-deploy-workflow
# To connect Azure kubectl: https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-cli#connect-to-the-cluster

name: Build and push the latest build to staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [master]
    paths:
      - "infrastructure/k8s/**"
      - "infrastructure/k8s-prod/**"
  pull_request:
    branches: [master]
    paths:
      - "infrastructure/k8s/**"
      - "infrastructure/k8s-prod/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          # Resource Group Name
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          # AKS Cluster Name
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
          # AKS Cluster Subscription
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: kubectl apply -f infrastructure/k8s && kubectl apply -f infrastructure/k8s-prod
